stages:
  data_split:
    cmd: python src/data_split.py
    deps:
    - data/pool_data
    - src/data_split.py
    params:
    - base
    - data_split
    outs:
    - data/test_data
    - data/train_data
  train:
    cmd: python src/train.py
    deps:
    - data/train_data
    - src/train.py
    params:
    - base
    - train
    outs:
    - models/model.pkl
  evaluate:
    cmd: python src/evaluate.py
    deps:
    - data/test_data
    - models/model.pkl
    - src/evaluate.py
    params:
    - base
    - evaluate
artifacts:
  cv:
    path: models
    type: model
    labels:
    - cv
  pool-segmentation:
    path: models/model.pkl
    desc: "This is a Computer Vision (CV) project that solves the problem of segmenting
      out swimming pools from satellite images.\n"
    type: model
    labels:
    - cv
    - segmentation
    - satellite-images
